services:
  - type: web
    name: rag-copywriter-icp-ti
    env: python
    plan: free            # ou starter/plus se quiser mais recursos
    region: oregon        # ou frankfurt (ajuste conforme sua latência)
    buildCommand: |
      pip install -r requirements.txt
      python scripts/embed.py            # gera data/index/rag_index.jsonl no build
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: TOP_K
        value: "12"
      - key: TOP_K_FINAL
        value: "6"
      - key: PYTHON_VERSION
        value: "3.11.9"
